const byId = (basePath: string, id: string) => `${basePath}/${id}`

const ADMIN = '/api/v1/admin'

export const API_ENDPOINTS = {
  auth: {
    login: `${ADMIN}/auth/login`,
    refreshToken: `${ADMIN}/auth/refresh-token`,
    revokeToken: `${ADMIN}/auth/revoke-token`,
    currentUser: `${ADMIN}/auth/current-user`,
    forgotPassword: `${ADMIN}/auth/password/forgot`,
    resetPassword: `${ADMIN}/auth/password/reset`,
    changePassword: `${ADMIN}/auth/password/change`,
    profile: `${ADMIN}/auth/profile`,
    permissions: `${ADMIN}/auth/permissions`,
    invitationVerify: `${ADMIN}/auth/invitation/verify`,
    // Kept only so old, unrouted registration modules still compile during the cutover.
    // The dashboard router does not expose public registration.
    register: '/api/v1/auth/register',
    verifyRegistration: '/api/v1/auth/register/verify',
  },
  dashboard: {
    summary: `${ADMIN}/dashboard/summary`,
  },
  ads: {
    list: `${ADMIN}/ads`,
    detail: (id: string) => byId(`${ADMIN}/ads`, id),
    create: `${ADMIN}/ads`,
    update: (id: string) => byId(`${ADMIN}/ads`, id),
    remove: (id: string) => byId(`${ADMIN}/ads`, id),
  },
  classes: {
    list: `${ADMIN}/classes`,
    brief: `${ADMIN}/classes/brief`,
    detail: (id: string) => byId(`${ADMIN}/classes`, id),
    create: `${ADMIN}/classes`,
    update: (id: string) => byId(`${ADMIN}/classes`, id),
    remove: (id: string) => byId(`${ADMIN}/classes`, id),
  },
  subjects: {
    list: `${ADMIN}/subjects`,
    brief: `${ADMIN}/subjects/brief`,
    detail: (id: string) => byId(`${ADMIN}/subjects`, id),
    create: `${ADMIN}/subjects`,
    update: (id: string) => byId(`${ADMIN}/subjects`, id),
    remove: (id: string) => byId(`${ADMIN}/subjects`, id),
  },
  units: {
    list: `${ADMIN}/units`,
    brief: `${ADMIN}/units/brief`,
    detail: (id: string) => byId(`${ADMIN}/units`, id),
    create: `${ADMIN}/units`,
    update: (id: string) => byId(`${ADMIN}/units`, id),
    remove: (id: string) => byId(`${ADMIN}/units`, id),
  },
  lessons: {
    list: `${ADMIN}/lessons`,
    brief: `${ADMIN}/lessons/brief`,
    detail: (id: string) => byId(`${ADMIN}/lessons`, id),
    create: `${ADMIN}/lessons`,
    update: (id: string) => byId(`${ADMIN}/lessons`, id),
    remove: (id: string) => byId(`${ADMIN}/lessons`, id),
  },
  teachers: {
    list: `${ADMIN}/teachers`,
    brief: `${ADMIN}/teachers/brief`,
    detail: (id: string) => byId(`${ADMIN}/teachers`, id),
    create: `${ADMIN}/teachers`,
    update: (id: string) => byId(`${ADMIN}/teachers`, id),
    remove: (id: string) => byId(`${ADMIN}/teachers`, id),
  },
  students: {
    list: `${ADMIN}/students`,
    brief: `${ADMIN}/students/brief`,
    detail: (id: string) => byId(`${ADMIN}/students`, id),
    create: `${ADMIN}/students`,
    update: (id: string) => byId(`${ADMIN}/students`, id),
    remove: (id: string) => byId(`${ADMIN}/students`, id),
  },
  employees: {
    list: `${ADMIN}/employees`,
    permissions: `${ADMIN}/employees/permissions`,
    detail: (id: string) => byId(`${ADMIN}/employees`, id),
    create: `${ADMIN}/employees`,
    update: (id: string) => byId(`${ADMIN}/employees`, id),
    remove: (id: string) => byId(`${ADMIN}/employees`, id),
    disable: (id: string) => `${ADMIN}/employees/${id}/disable`,
    enable: (id: string) => `${ADMIN}/employees/${id}/enable`,
    resendInvitation: (id: string) => `${ADMIN}/employees/${id}/resend-invitation`,
    auditLogs: (id: string) => `${ADMIN}/employees/${id}/audit-logs`,
  },
  quizzes: {
    list: `${ADMIN}/quizzes`,
    brief: `${ADMIN}/quizzes/brief`,
    detail: (id: string) => byId(`${ADMIN}/quizzes`, id),
    create: `${ADMIN}/quizzes`,
    update: (id: string) => byId(`${ADMIN}/quizzes`, id),
    remove: (id: string) => byId(`${ADMIN}/quizzes`, id),
  },
  questions: {
    list: `${ADMIN}/questions`,
    detail: (id: string) => byId(`${ADMIN}/questions`, id),
    create: `${ADMIN}/questions`,
    update: (id: string) => byId(`${ADMIN}/questions`, id),
    remove: (id: string) => byId(`${ADMIN}/questions`, id),
  },
  resources: {
    list: `${ADMIN}/resources`,
    detail: (id: string) => byId(`${ADMIN}/resources`, id),
    content: (id: string) => `${ADMIN}/resources/${id}/content`,
    byEntity: (entityId: string) => `${ADMIN}/resources/entity/${entityId}`,
    upload: `${ADMIN}/resources`,
    update: (id: string) => byId(`${ADMIN}/resources`, id),
    updateFile: (id: string) => `${ADMIN}/resources/${id}/file`,
    remove: (id: string) => byId(`${ADMIN}/resources`, id),
  },
  courses: {
    list: `${ADMIN}/courses`,
    detail: (id: string) => byId(`${ADMIN}/courses`, id),
    create: `${ADMIN}/courses`,
    update: (id: string) => byId(`${ADMIN}/courses`, id),
    remove: (id: string) => byId(`${ADMIN}/courses`, id),
    status: (id: string) => `${ADMIN}/courses/${id}/status`,
    sessions: (courseId: string) => `${ADMIN}/courses/${courseId}/sessions`,
    purchases: (courseId: string) => `${ADMIN}/courses/${courseId}/purchases`,
    qr: (courseId: string) => `${ADMIN}/courses/${courseId}/qr`,
  },
  courseSessions: {
    detail: (id: string) => byId(`${ADMIN}/course-sessions`, id),
    update: (id: string) => byId(`${ADMIN}/course-sessions`, id),
    remove: (id: string) => byId(`${ADMIN}/course-sessions`, id),
    materials: (sessionId: string) => `${ADMIN}/course-sessions/${sessionId}/materials`,
    comments: (sessionId: string) => `${ADMIN}/course-sessions/${sessionId}/comments`,
    notes: (sessionId: string) => `${ADMIN}/course-sessions/${sessionId}/notes`,
  },
  courseMaterials: {
    detail: (id: string) => byId(`${ADMIN}/course-materials`, id),
    update: (id: string) => byId(`${ADMIN}/course-materials`, id),
    remove: (id: string) => byId(`${ADMIN}/course-materials`, id),
    download: (id: string) => `${ADMIN}/course-materials/${id}/download`,
    stream: (id: string) => `${ADMIN}/course-materials/${id}/stream`,
    playback: (id: string) => `${ADMIN}/course-materials/${id}/playback`,
    offlineManifest: (id: string) => `${ADMIN}/course-materials/${id}/offline-download/manifest`,
    hlsPlaylist: (id: string) => `${ADMIN}/course-materials/${id}/hls/index.m3u8`,
    hlsKey: (id: string) => `${ADMIN}/course-materials/${id}/hls/key`,
    hlsSegment: (id: string, fileName: string) =>
      `${ADMIN}/course-materials/${id}/hls/${encodeURIComponent(fileName)}`,
    hlsRetry: (id: string) => `${ADMIN}/course-materials/${id}/hls/retry`,
  },
  notifications: {
    list: `${ADMIN}/notifications`,
    push: `${ADMIN}/notifications/push`,
    create: `${ADMIN}/notifications/push`,
    devices: `${ADMIN}/notifications/devices`,
    byUser: (userId: string) => `${ADMIN}/notifications/users/${userId}`,
    markUserRead: (userId: string) => `${ADMIN}/notifications/users/${userId}/read`,
  },
  pageContents: {
    list: `${ADMIN}/page-contents`,
    detail: (id: string) => byId(`${ADMIN}/page-contents`, id),
    create: `${ADMIN}/page-contents`,
    update: (id: string) => byId(`${ADMIN}/page-contents`, id),
    remove: (id: string) => byId(`${ADMIN}/page-contents`, id),
  },
  pointsOfSale: {
    list: `${ADMIN}/points-of-sale`,
    detail: (id: string) => byId(`${ADMIN}/points-of-sale`, id),
    create: `${ADMIN}/points-of-sale`,
    update: (id: string) => byId(`${ADMIN}/points-of-sale`, id),
    remove: (id: string) => byId(`${ADMIN}/points-of-sale`, id),
  },
  qrCodes: {
    list: `${ADMIN}/qr`,
    detail: (id: string) => `${ADMIN}/qr/bundles/${id}`,
    create: `${ADMIN}/qr`,
    remove: (id: string) => `${ADMIN}/qr/${id}`,
  },
  ai: {
    plans: `${ADMIN}/ai/plans`,
    subscriptions: `${ADMIN}/ai/subscriptions`,
    analytics: `${ADMIN}/ai/analytics`,
    documents: `${ADMIN}/ai/documents`,
    documentUpload: `${ADMIN}/ai/documents/upload`,
    maintenanceRetry: `${ADMIN}/ai/maintenance/retry-rag-deletions`,
  },
  // Compatibility-only modules that are not part of the active Quizy admin cutover.
  pages: {
    list: '/api/Pages',
    detail: '/api/Pages/:id',
    create: '/api/Pages',
    update: '/api/Pages/:id',
    remove: '/api/Pages/:id',
  },
  projects: {
    list: '/api/Projects',
    detail: '/api/Projects/:id',
    create: '/api/Projects',
    update: '/api/Projects/:id',
    remove: '/api/Projects/:id',
    reorder: '/api/Projects/reorder',
    addMedia: '/api/Projects/:id/media',
    removeMedia: '/api/Projects/:id/media/:mediaId',
  },
  faqs: {
    list: '/api/Faqs',
    detail: '/api/Faqs/:id',
    create: '/api/Faqs',
    update: '/api/Faqs/:id',
    remove: '/api/Faqs/:id',
  },
} as const
