const byId = (basePath: string, id: string) => `${basePath}/${id}`

export const API_ENDPOINTS = {
  auth: {
    login: '/api/Auth/login',
    currentUser: '/api/Auth/current-user',
    register: '/api/Auth/register',
    verifyRegistration: '/api/Auth/register/verify',
    forgotPassword: '/api/Auth/password/forgot',
    resetPassword: '/api/Auth/password/reset',
    changePassword: '/api/Auth/password/change',
    profile: '/api/Auth/profile',
  },
  ads: {
    list: '/api/Ads',
    detail: (id: string) => byId('/api/Ads', id),
    create: '/api/Ads',
    update: (id: string) => byId('/api/Ads', id),
    remove: (id: string) => byId('/api/Ads', id),
  },
  classes: {
    list: '/api/Classes',
    brief: '/api/Classes/Brief',
    detail: (id: string) => byId('/api/Classes', id),
    create: '/api/Classes',
    update: (id: string) => byId('/api/Classes', id),
    remove: (id: string) => byId('/api/Classes', id),
  },
  subjects: {
    list: '/api/Subjects',
    brief: '/api/Subjects/Brief',
    detail: (id: string) => byId('/api/Subjects', id),
    create: '/api/Subjects',
    update: (id: string) => byId('/api/Subjects', id),
    remove: (id: string) => byId('/api/Subjects', id),
  },
  units: {
    list: '/api/Units',
    brief: '/api/Units/Brief',
    detail: (id: string) => byId('/api/Units', id),
    create: '/api/Units',
    update: (id: string) => byId('/api/Units', id),
    remove: (id: string) => byId('/api/Units', id),
  },
  lessons: {
    list: '/api/Lessons',
    brief: '/api/Lessons/Brief',
    bulkCreate: '/api/Lessons/List',
    detail: (id: string) => byId('/api/Lessons', id),
    create: '/api/Lessons',
    update: (id: string) => byId('/api/Lessons', id),
    remove: (id: string) => byId('/api/Lessons', id),
  },
  teachers: {
    list: '/api/Teachers',
    brief: '/api/Teachers/Brief',
    detail: (id: string) => byId('/api/Teachers', id),
    create: '/api/Teachers',
    update: (id: string) => byId('/api/Teachers', id),
    remove: (id: string) => byId('/api/Teachers', id),
  },
  students: {
    list: '/api/Students',
    brief: '/api/Students/Brief',
    detail: (id: string) => byId('/api/Students', id),
    create: '/api/Students',
    update: (id: string) => byId('/api/Students', id),
    remove: (id: string) => byId('/api/Students', id),
  },
  quizzes: {
    list: '/api/Quizes',
    detail: (id: string) => byId('/api/Quizes', id),
    create: '/api/Quizes',
    update: (id: string) => byId('/api/Quizes', id),
    remove: (id: string) => byId('/api/Quizes', id),
  },
  questions: {
    list: '/api/Qestions',
    detail: (id: string) => byId('/api/Qestions', id),
    create: '/api/Qestions',
    update: (id: string) => byId('/api/Qestions', id),
    remove: (id: string) => byId('/api/Qestions', id),
  },
  resources: {
    list: '/api/Resources',
    detail: (id: string) => byId('/api/Resources', id),
    upload: '/api/Resources',
    remove: (id: string) => byId('/api/Resources', id),
  },
  courses: {
    list: '/api/Courses',
    accessible: '/api/Courses/accessible',
    detail: (id: string) => byId('/api/Courses', id),
    create: '/api/Courses',
    update: (id: string) => byId('/api/Courses', id),
    remove: (id: string) => byId('/api/Courses', id),
    sessions: (courseId: string) => `/api/Courses/${courseId}/sessions`,
    qr: (courseId: string) => `/api/Courses/${courseId}/qr`,
    purchaseStatus: (courseId: string) => `/api/Courses/${courseId}/purchase-status`,
  },
  courseSessions: {
    detail: (id: string) => byId('/api/CourseSessions', id),
    update: (id: string) => byId('/api/CourseSessions', id),
    remove: (id: string) => byId('/api/CourseSessions', id),
    materials: (sessionId: string) => `/api/CourseSessions/${sessionId}/materials`,
    comments: (sessionId: string) => `/api/CourseSessions/${sessionId}/comments`,
    notes: (sessionId: string) => `/api/CourseSessions/${sessionId}/notes`,
  },
  courseMaterials: {
    detail: (id: string) => byId('/api/CourseMaterials', id),
    update: (id: string) => byId('/api/CourseMaterials', id),
    remove: (id: string) => byId('/api/CourseMaterials', id),
    download: (id: string) => `/api/CourseMaterials/${id}/download`,
    stream: (id: string) => `/api/CourseMaterials/${id}/stream`,
  },
  courseComments: {
    detail: (id: string) => byId('/api/CourseComments', id),
    update: (id: string) => byId('/api/CourseComments', id),
    remove: (id: string) => byId('/api/CourseComments', id),
  },
  courseTeacherNotes: {
    detail: (id: string) => byId('/api/CourseTeacherNotes', id),
    update: (id: string) => byId('/api/CourseTeacherNotes', id),
    remove: (id: string) => byId('/api/CourseTeacherNotes', id),
  },
  notifications: {
    list: '/api/Notifications',
    detail: (id: string) => byId('/api/Notifications', id),
    create: '/api/Notifications',
    update: (id: string) => byId('/api/Notifications', id),
    remove: (id: string) => byId('/api/Notifications', id),
    devices: '/api/Notifications/devices',
  },
  pageContents: {
    list: '/api/PageContents',
    detail: (id: string) => byId('/api/PageContents', id),
    create: '/api/PageContents',
    update: (id: string) => byId('/api/PageContents', id),
    remove: (id: string) => byId('/api/PageContents', id),
  },
  pointsOfSale: {
    list: '/api/PointsOfSale',
    detail: (id: string) => byId('/api/PointsOfSale', id),
    create: '/api/PointsOfSale',
    update: (id: string) => byId('/api/PointsOfSale', id),
    remove: (id: string) => byId('/api/PointsOfSale', id),
  },
  qrCodes: {
    list: '/api/QrCodes',
    detail: (id: string) => byId('/api/QrCodes', id),
    create: '/api/QrCodes',
    update: (id: string) => byId('/api/QrCodes', id),
    remove: (id: string) => byId('/api/QrCodes', id),
  },
  statistics: {
    list: '/api/Statistics',
  },
} as const
