export const API_ENDPOINTS = {
  auth: {
    login: '/api/v1/admin/login',
    logout: '/api/v1/admin/logout',
    forgotPassword: '/api/v1/admin/forgot-password',
    forgetPassword: '/api/v1/admin/forget-password',
  },
  homeContent: {
    detail: '/api/v1/admin/home-content',
    update: '/api/v1/admin/home-content',
    addMedia: '/api/v1/admin/home-content/media',
    removeMedia: '/api/v1/admin/home-content/media/:mediaId',
  },
  homeStats: {
    detail: '/api/v1/admin/home-stats',
    update: '/api/v1/admin/home-stats',
  },
  homeStatCards: {
    list: '/api/v1/admin/home-stat-cards',
    reorder: '/api/v1/admin/home-stat-cards/reorder',
    detail: '/api/v1/admin/home-stat-cards/:id',
    create: '/api/v1/admin/home-stat-cards',
    update: '/api/v1/admin/home-stat-cards/:id',
    remove: '/api/v1/admin/home-stat-cards/:id',
  },
  membershipBenefits: {
    detail: '/api/v1/admin/membership-benefits',
    update: '/api/v1/admin/membership-benefits',
  },
  membershipBenefitCards: {
    list: '/api/v1/admin/membership-benefit-cards',
    reorder: '/api/v1/admin/membership-benefit-cards/reorder',
    detail: '/api/v1/admin/membership-benefit-cards/:id',
    create: '/api/v1/admin/membership-benefit-cards',
    update: '/api/v1/admin/membership-benefit-cards/:id',
    remove: '/api/v1/admin/membership-benefit-cards/:id',
  },
  homeHighlights: {
    list: '/api/v1/admin/home-highlights',
    reorder: '/api/v1/admin/home-highlights/reorder',
    detail: '/api/v1/admin/home-highlights/:id',
    create: '/api/v1/admin/home-highlights',
    update: '/api/v1/admin/home-highlights/:id',
    remove: '/api/v1/admin/home-highlights/:id',
  },
  homeAboutTabs: {
    list: '/api/v1/admin/home-about-tabs',
    reorder: '/api/v1/admin/home-about-tabs/reorder',
    detail: '/api/v1/admin/home-about-tabs/:id',
    create: '/api/v1/admin/home-about-tabs',
    update: '/api/v1/admin/home-about-tabs/:id',
    remove: '/api/v1/admin/home-about-tabs/:id',
  },
  homeAboutTabCards: {
    list: '/api/v1/admin/home-about-tab-cards',
    reorder: '/api/v1/admin/home-about-tab-cards/reorder',
    detail: '/api/v1/admin/home-about-tab-cards/:id',
    create: '/api/v1/admin/home-about-tab-cards',
    update: '/api/v1/admin/home-about-tab-cards/:id',
    remove: '/api/v1/admin/home-about-tab-cards/:id',
  },
  pages: {
    list: '/api/v1/admin/pages',
    detail: '/api/v1/admin/pages/:id',
    create: '/api/v1/admin/pages',
    update: '/api/v1/admin/pages/:id',
    remove: '/api/v1/admin/pages/:id',
  },
  projects: {
    list: '/api/v1/admin/projects',
    reorder: '/api/v1/admin/projects/reorder',
    detail: '/api/v1/admin/projects/:id',
    create: '/api/v1/admin/projects',
    update: '/api/v1/admin/projects/:id',
    remove: '/api/v1/admin/projects/:id',
    addMedia: '/api/v1/admin/projects/:id/media',
    removeMedia: '/api/v1/admin/projects/:id/media/:mediaId',
  },
  pageSections: {
    list: '/api/v1/admin/page-sections',
    reorder: '/api/v1/admin/page-sections/reorder',
    detail: '/api/v1/admin/page-sections/:id',
    create: '/api/v1/admin/page-sections',
    update: '/api/v1/admin/page-sections/:id',
    remove: '/api/v1/admin/page-sections/:id',
    addMedia: '/api/v1/admin/page-sections/:id/media',
    removeMedia: '/api/v1/admin/page-sections/:id/media/:mediaId',
  },
  sectionItems: {
    list: '/api/v1/admin/section-items',
    detail: '/api/v1/admin/section-items/:id',
    create: '/api/v1/admin/section-items',
    update: '/api/v1/admin/section-items/:id',
    remove: '/api/v1/admin/section-items/:id',
  },
  boardMembers: {
    list: '/api/v1/admin/board-members',
    reorder: '/api/v1/admin/board-members/reorder',
    detail: '/api/v1/admin/board-members/:id',
    create: '/api/v1/admin/board-members',
    update: '/api/v1/admin/board-members/:id',
    remove: '/api/v1/admin/board-members/:id',
    addMedia: '/api/v1/admin/board-members/:id/media',
    removeMedia: '/api/v1/admin/board-members/:id/media/:mediaId',
  },
  galleryItems: {
    list: '/api/v1/admin/gallery-items',
    reorder: '/api/v1/admin/gallery-items/reorder',
    detail: '/api/v1/admin/gallery-items/:id',
    create: '/api/v1/admin/gallery-items',
    update: '/api/v1/admin/gallery-items/:id',
    remove: '/api/v1/admin/gallery-items/:id',
    addMedia: '/api/v1/admin/gallery-items/:id/media',
    removeMedia: '/api/v1/admin/gallery-items/:id/media/:mediaId',
  },
  faqs: {
    list: '/api/v1/admin/faqs',
    reorder: '/api/v1/admin/faqs/reorder',
    detail: '/api/v1/admin/faqs/:id',
    create: '/api/v1/admin/faqs',
    update: '/api/v1/admin/faqs/:id',
    remove: '/api/v1/admin/faqs/:id',
  },
  footerLinks: {
    list: '/api/v1/admin/footer-links',
    reorder: '/api/v1/admin/footer-links/reorder',
    detail: '/api/v1/admin/footer-links/:id',
    create: '/api/v1/admin/footer-links',
    update: '/api/v1/admin/footer-links/:id',
    remove: '/api/v1/admin/footer-links/:id',
  },
  contactInfos: {
    list: '/api/v1/admin/contact-infos',
    detail: '/api/v1/admin/contact-infos/:id',
    create: '/api/v1/admin/contact-infos',
    update: '/api/v1/admin/contact-infos/:id',
    remove: '/api/v1/admin/contact-infos/:id',
  },
  contactMessages: {
    list: '/api/v1/admin/contact-messages',
    detail: '/api/v1/admin/contact-messages/:id',
    remove: '/api/v1/admin/contact-messages/:id',
    updateStatus: '/api/v1/admin/contact-messages/:id/status',
  },
  fileManager: {
    uploadMedia: '/api/v1/admin/file-manager/media',
    deletePoolMedia: '/api/v1/admin/file-manager/media',
    attachMedia: '/api/v1/admin/file-manager/media/attach',
    detachMedia: '/api/v1/admin/file-manager/media/detach',
    replaceMedia: '/api/v1/admin/file-manager/media/:mediaId/replace',
  },
} as const
